version: '3.8'

services:
  nwapi-app:
    image: nwerp-api:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nwerp.api
    environment:
      - ConnectionStrings__OracleDbConnection=User Id=${ORACLE_DB_USER};Password=${ORACLE_DB_PASSWORD};Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=${ORACLE_DB_HOST})(PORT=${ORACLE_DB_PORT})))(CONNECT_DATA=(SERVICE_NAME=${ORACLE_DB_SERVICE})))      
      - ConnectionStrings__SqlServerConnection=Server=${SQL_SERVER_HOST};Database=${SQL_SERVER_DB};User Id=${SQL_SERVER_USER};Password=${SQL_SERVER_PASSWORD};Encrypt=False;TrustServerCertificate=True;
      - JobsToRun__0=${JOB_RUN_0}
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=${DOTNET_SYSTEM_GLOBALIZATION_INVARIANT}
      - TZ=${TZ}
      - LANG=${LANG}    
    ports:
      - "${API_PORT}:8080"
    volumes:
      # Usando a letra da unidade (Windows)
      - 'M:\:/mnt/xmlnotafiscal/'
      # Ou usando o caminho UNC (Windows)
      # - "\\\\servidor\\compartilhamento:/app/unidade_rede"
      # Para Linux ou macOS
      # - '/mnt/unidade_rede:/app/unidade_rede'