# Etapa 1: Imagem Base
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /app

# Configuração de Variáveis de Ambiente
ENV ORACLE_HOME=/opt/oracle
ENV LD_LIBRARY_PATH=$ORACLE_HOME/instantclient_19_24
ENV PATH=$ORACLE_HOME:$PATH

USER root
ARG TARGETARCH="arm64"

# Criando o diretório de configuração do Oracle e definindo permissões
RUN mkdir -p $ORACLE_HOME/instantclient_19_24/network/admin && chmod -R 755 $ORACLE_HOME

# Instalando Dependências Necessárias
RUN apt-get update && apt-get install -y \
    unzip \
    libaio1 \
    libaio-dev \
    wget \
    libssl-dev \
    libpq-dev \
    libkrb5-dev \
    libsasl2-dev \
    libssl3 \
    build-essential \
    ca-certificates \
    libstdc++6 \
    zlib1g \
    apt-utils \
    curl \
    git \
    rsync \
    vim \
    ssh \
    tzdata \
    locales \
    gnupg2 \
    apt-transport-https \
    gnupg &&\
    rm -rf /var/lib/apt/lists/* &&\
    echo "pt_BR.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen pt_BR.UTF-8 && \
    update-locale LANG=pt_BR.UTF-8 LC_ALL=pt_BR.UTF-8 &&\
    echo "America/Sao_Paulo" > /etc/timezone

# Instalando o Oracle Instant Client de Acordo com a Arquitetura
RUN set -ex && \
    if [ "$TARGETARCH" = "amd64" ]; then \
        echo "Baixando pacotes para amd64..." && \
        wget -q https://download.oracle.com/otn_software/linux/instantclient/oracle-instantclient-basiclite-linuxx64.zip && \
        wget -q https://download.oracle.com/otn_software/linux/instantclient/oracle-instantclient-devel-linuxx64.zip && \
        wget -q https://download.oracle.com/otn_software/linux/instantclient/oracle-instantclient-sqlplus-linuxx64.zip && \
        echo "Extraindo pacotes..." && \
        unzip -o -q oracle-instantclient-basiclite-linuxx64.zip -d $ORACLE_HOME && \
        unzip -o -q oracle-instantclient-devel-linuxx64.zip -d $ORACLE_HOME && \
        unzip -o -q oracle-instantclient-sqlplus-linuxx64.zip -d $ORACLE_HOME && \
        rm -f oracle-instantclient-*.zip; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        echo "Baixando pacotes para arm64..." && \
        wget -q https://download.oracle.com/otn_software/linux/instantclient/1924000/instantclient-basic-linux.arm64-19.24.0.0.0dbru.zip && \
        wget -q https://download.oracle.com/otn_software/linux/instantclient/1924000/instantclient-sdk-linux.arm64-19.24.0.0.0dbru.zip && \
        wget -q https://download.oracle.com/otn_software/linux/instantclient/1924000/instantclient-tools-linux.arm64-19.24.0.0.0dbru.zip && \
        wget -q https://download.oracle.com/otn_software/linux/instantclient/1924000/instantclient-sqlplus-linux.arm64-19.24.0.0.0dbru.zip && \
        echo "Extraindo pacotes..." && \
        unzip -o -q instantclient-basic-linux.arm64-19.24.0.0.0dbru.zip -d $ORACLE_HOME && \
        unzip -o -q instantclient-sdk-linux.arm64-19.24.0.0.0dbru.zip -d $ORACLE_HOME && \
        unzip -o -q instantclient-sqlplus-linux.arm64-19.24.0.0.0dbru.zip -d $ORACLE_HOME && \
        unzip -o -q instantclient-tools-linux.arm64-19.24.0.0.0dbru.zip -d $ORACLE_HOME && \
        rm -f instantclient-*.zip; \
    else \
        echo "Arquitetura não suportada: $TARGETARCH" && exit 1; \
    fi

# Instalando o Cliente SQL Server (MS ODBC Driver) e Ferramentas SQLCMD
RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc && \
    curl -sSL https://packages.microsoft.com/config/ubuntu/22.04/prod.list | tee /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 && \
    apt-get install -y unixodbc-dev && \
    echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Finalizando a imagem base
FROM base